---
- hosts: localhost
  become: yes
  tasks:
  - name: Install apache on Redhat Server
    yum: 
     name: httpd
     state: present
    when: not ansible_os_family == "Redhat" 
  - name: Install apache on Ubuntu Server
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"
  - name: Print free Memory
    debug: 
     msg: "free memory is {{ansible_memory_mb.real.free}}" 
