---
- hosts: all
  become: yes
  tasks:
  - name: Install apache server
    yum:
      name: httpd
      state: present
  - name: Ensure apache server is running
    service:
      name: httpd
      enabled: yes
      state: started