---
- hosts: all
  tasks:
  - name: Find who is executing
    command: whoami
  - name: Ping all
    ping:
  - name: To get the current directory
    command: pwd
  - name: Uninstall tree
    yum:
      name: tree
      state: absent